server:
    port: 8081
graphql:
    spqr:
        gui:
            enabled: true
            target-endpoint: '/graphql'
            target-ws-endpoint: '/graphql'
logging:
    pattern:
        console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'